services:
  adapter:
    build: ./adapter-service
    ports:
      - "8080:8080"

  mock:
    build: ./external-mock-service
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"